/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItinerariesIndexRouteImport } from './routes/itineraries.index'
import { Route as ItinerariesBaliRouteImport } from './routes/itineraries.bali'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIndexRoute = ItinerariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItinerariesRoute,
} as any)
const ItinerariesBaliRoute = ItinerariesBaliRouteImport.update({
  id: '/bali',
  path: '/bali',
  getParentRoute: () => ItinerariesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/media-kit': typeof MediaKitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/itineraries/bali': typeof ItinerariesBaliRoute
  '/itineraries/': typeof ItinerariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/media-kit': typeof MediaKitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/itineraries/bali': typeof ItinerariesBaliRoute
  '/itineraries': typeof ItinerariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/media-kit': typeof MediaKitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/itineraries/bali': typeof ItinerariesBaliRoute
  '/itineraries/': typeof ItinerariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/itineraries'
    | '/media-kit'
    | '/sitemap.xml'
    | '/itineraries/bali'
    | '/itineraries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/media-kit'
    | '/sitemap.xml'
    | '/itineraries/bali'
    | '/itineraries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/itineraries'
    | '/media-kit'
    | '/sitemap.xml'
    | '/itineraries/bali'
    | '/itineraries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ItinerariesRoute: typeof ItinerariesRouteWithChildren
  MediaKitRoute: typeof MediaKitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/': {
      id: '/itineraries/'
      path: '/'
      fullPath: '/itineraries/'
      preLoaderRoute: typeof ItinerariesIndexRouteImport
      parentRoute: typeof ItinerariesRoute
    }
    '/itineraries/bali': {
      id: '/itineraries/bali'
      path: '/bali'
      fullPath: '/itineraries/bali'
      preLoaderRoute: typeof ItinerariesBaliRouteImport
      parentRoute: typeof ItinerariesRoute
    }
  }
}

interface ItinerariesRouteChildren {
  ItinerariesBaliRoute: typeof ItinerariesBaliRoute
  ItinerariesIndexRoute: typeof ItinerariesIndexRoute
}

const ItinerariesRouteChildren: ItinerariesRouteChildren = {
  ItinerariesBaliRoute: ItinerariesBaliRoute,
  ItinerariesIndexRoute: ItinerariesIndexRoute,
}

const ItinerariesRouteWithChildren = ItinerariesRoute._addFileChildren(
  ItinerariesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ItinerariesRoute: ItinerariesRouteWithChildren,
  MediaKitRoute: MediaKitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
